### ISSUE TITLE
Why not label this as an awesome list?

### ISSUE THREAD

**Issue by MadhavBahl** [GDGAhmedabad/Awesome-Learning-Resources#258]
The content is very organized and helpful. How about you label it awesome?

**Comment by PareshMayani** [comment]
Hi Madhav, that's a great suggestion. Can you please help us in choosing best labels for the reply and start using the same? Pls share your suggestions

**Comment by MadhavBahlMD** [comment]
Here, see the list of all badges https://shields.io/
Also, do change the name of repo from Learning-Resources to `Awesome-Learning-Resources` :)
And do add an awesome badge :)

**Comment by MadhavBahlMD** [comment]
Also, I wrote this article long back, https://medium.com/@madhavbahl10/a-practical-approach-to-web-development-1ee37a4ad829
You can put it's link too in the resources, if its fine :)

**Comment by PareshMayani** [comment]
Hi @MadhavBahl , apology for the late action, but yeah finally we have made the changes as suggested. Thank you again and keep suggesting and contributing!
